select * from customer limit 20
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue from customer group by gender
--Q2.Which gender spends more on average?
select gender,ROUND(AVG(purchase_amount),2)as avg_spend from customer group by gender
--Q3.Which top 10 locations generate the highest revenue?
select location,SUM(purchase_amount) as total_revenue from customer group by location LIMIT 10
--Q4.Do subscribed customers have more previous purchases?
Select subscription_status,ROUND(AVG(previous_purchases), 2) as avg_previous_purchases from customer group by subscription_status
--Q5.Which categories generate the highest revenue?
Select category,SUM(purchase_amount) as total_revenue from customer group by category order by total_revenue desc
--Q6.Which seasons generate the most revenue?
Select season,SUM(purchase_amount) as total_revenue from customer group by season order by total_revenue desc
--Q7.Which categories receive the highest customer ratings?
Select category,ROUND(AVG(review_rating::numeric), 2) as avg_rating from customer group by category order by avg_rating desc
--Q8.Which payment method is used the most?
select payment_method,COUNT(*) as usage from customer group by payment_method order by usage desc
--Q9.Which shipping methods receive the best ratings?
select shipping_type, ROUND(AVG(review_rating::numeric), 2) as avg_rating from customer group by shipping_type order by avg_rating desc
--Q10.Which high-revenue categories have lower customer satisfaction?
select category,SUM(purchase_amount) as total_revenue, ROUND(AVG(review_rating::numeric), 2) as avg_rating from customer group by category
order by total_revenue desc,avg_rating 
